### ISSUE TITLE
Cannot deobfuscate

### ISSUE THREAD

**Issue by DimitarDechew** [0x1Avram/js-deobfuscator#13]
Hello,
How can I contact you so we could discuss future private updates of this repository?

**Comment by 0x1Avram** [comment]
This is an open source project, so I am not sure what this means, but you can DM me here or, if you prefer mail, I’ve given it here - https://github.com/0x1Avram/js-deobfuscator/issues/8#issuecomment-1236172934

**Comment by DimitarDechew** [comment]
> This is an open source project, so I am not sure what this means, but you can DM me here or, if you prefer mail, I’ve given it here - [#8 (comment)](https://github.com/0x1Avram/js-deobfuscator/issues/8#issuecomment-1236172934)

I've sent you an email

**Comment by DimitarDechew** [comment]
Hello,
I just tried out the latest version and that's what I got:

`error: [deobfuscator.js] Error when transforming the input source code to AST. This is an 'esprima' parser limitation and the code needs to be transpiled to an esprima compatible version before passing it to the deobfuscator. error = Error: Line 1: Unexpected token ;. Stack = Error: Line 1: Unexpected token ;
    at ErrorHandler.constructError (E:\Programming\js-deobfuscator-1.0.4\node_modules\esprima\dist\esprima.js:5012:22)
    at ErrorHandler.createError (E:\Programming\js-deobfuscator-1.0.4\node_modules\esprima\dist\esprima.js:5028:27)
    at Parser.unexpectedTokenError (E:\Programming\js-deobfuscator-1.0.4\node_modules\esprima\dist\esprima.js:1985:39)
    at Parser.throwUnexpectedToken (E:\Programming\js-deobfuscator-1.0.4\node_modules\esprima\dist\esprima.js:1995:21)
    at Parser.parseClassElement (E:\Programming\js-deobfuscator-1.0.4\node_modules\esprima\dist\esprima.js:4632:19)
    at Parser.parseClassElementList (E:\Programming\js-deobfuscator-1.0.4\node_modules\esprima\dist\esprima.js:4665:33)
    at Parser.parseClassBody (E:\Programming\js-deobfuscator-1.0.4\node_modules\esprima\dist\esprima.js:4673:33)
    at Parser.parseClassDeclaration (E:\Programming\js-deobfuscator-1.0.4\node_modules\esprima\dist\esprima.js:4687:31)
    at Parser.parseStatementListItem (E:\Programming\js-deobfuscator-1.0.4\node_modules\esprima\dist\esprima.js:3382:39)
    at Parser.parseModule (E:\Programming\js-deobfuscator-1.0.4\node_modules\esprima\dist\esprima.js:4715:29)
    at parse (E:\Programming\js-deobfuscator-1.0.4\node_modules\esprima\dist\esprima.js:122:38)
    at Object.parseModule (E:\Programming\js-deobfuscator-1.0.4\node_modules\esprima\dist\esprima.js:139:13)
    at Function.generateASTFromSourceCode (E:\Programming\js-deobfuscator-1.0.4\ast_operations.js:141:27)
    at SourceCodeDeobfuscator._generateASTFromObfuscatedSourceCode (E:\Programming\js-deobfuscator-1.0.4\deobfuscator.js:47:58)
    at SourceCodeDeobfuscator.deobfuscate (E:\Programming\js-deobfuscator-1.0.4\deobfuscator.js:31:18)
    at main (E:\Programming\js-deobfuscator-1.0.4\index.js:244:49)
    at Object.<anonymous> (E:\Programming\js-deobfuscator-1.0.4\index.js:256:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {"timestamp":"22:03:38"}
info: [index.js] Finished deobfuscation process. {"timestamp":"22:03:38"}`

Please, respond to my email I've messaged you with a great offer.

**Comment by 0x1Avram** [comment]
Hello,
I wanted to update the project before responding to your email.

The issue is that the deobfuscator uses the 'esprima' parser which is not actively maintained (the last release was ~4 years ago). Because of this, newer language features such as computed properties (https://www.javascripttutorial.net/es6/javascript-computed-property/)  are not supported by the parser and the deobfuscation is not attempted.

A workaround for this issue is first transpiling the JavaScript code to an older version of the language for which the esprima parser has support. One can do this using Babel and then run the deobfuscator on the output that generated by Babel. I Also found some small bugs where some function calls were not being replaced with their equivalent strings, so I created 1.0.5 to fix that and add a log message suggesting to transpile the code before deobfuscating it.

If you have other questions or find other issues, let me know.
